name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: |
          cd $GOPATH 
          pwd
          go list ... | grep gorilla
          o get -v -u github.com/gorilla/mux
          sudo go build -v ./...

    - name: Validate coverage Unit Test
      run: |
          ls
          for i in $(ls -C1)
          do
            echo [ ------ Unit Test $i ------ ]
            go test -v ./...
          done
      
